config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :login, to: 'sessions#new', as: 'login'
  delete :logout, to: 'sessions#destroy', as: 'logout'
  get :register, to: 'users#new', as: 'register'
  post :register, to: 'users#create'

  # External Authentication
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # Languge
  resources :languages, only: [] do
  	collection do
  		get	:english
  		get	:bahasa
  	end
  end

  scope "(:locale)" do
    resources :password_resets
	  resources	:users do
	  	member do
		    get :activate
		  end
		end
  	resources :sessions, except: [ :show ]

    resources :schedules do
      collection do
        get :redirect
        get :callback
        get :calendars
        post :events
        delete :reset
        post :import
      end
    end
    resources :events do
      member do
        # put :archive
        post :search_agenda
        put :set_date
      end
    end

    resources :invitations, only: [:create] do
      member do
        put :resent
      end
    end
	end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

	root 'dashboard#index'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	skip_before_action :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])
        
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
        
    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(login_path, notice: 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(login_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                <%= form_for @user, url: password_reset_path(id: @token), html: { method: :put, class: 'formValidation' } do |f| %>
                  <div class="card card-login card-hidden">
                    <div class="card-header text-center" data-background-color="purple">
                        <h4 class="card-title">Reset Password</h4>
                    </div>
                    <p class="category text-center">
                    </p>
                    <div class="card-content">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">email</i>
                            </span>
                            <div class="form-group form-success label-floating">
                                <label class="control-label"><%= t("authentication.signin.email") %></label>
                                <%= f.email_field :email, autofocus: true, class: 'form-control', disabled: true,  required: true %>
                            </div>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">lock_outline</i>
                            </span>
                            <div class="form-group form-success label-floating">
                                <label class="control-label"><%= t("authentication.signin.password") %></label>
                                <%= f.password_field :password, autocomplete: "off", class: 'form-control', required: true %>
                            </div>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">lock_outline</i>
                            </span>
                            <div class="form-group form-success label-floating">
                                <label class="control-label"><%= t("authentication.signin.password_cofirmation") %></label>
                                <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', required: true, "equalTo" => '#user_password' %>
                            </div>
                        </div>
                    </div>
                    <div class="footer text-center">
                        <%= f.submit "Reset My Password", class: "btn btn-primary btn-simple btn-wd btn-lg" %>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/password_resets/new.html.erb
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                <%= form_tag password_resets_path, method: :post, class: 'formValidation' do %>

                  <div class="card card-login card-hidden">
                    <div class="card-content">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">email</i>
                            </span>
                            <div class="form-group form-success label-floating">
                                <label class="control-label"><%= t("authentication.signin.email") %></label>
                                <%= text_field_tag :email, nil, autofocus: true, class: 'form-control',  required: true %>
                            </div>
                        </div>
                    </div>
                    <div class="footer text-center">
                        <%= submit_tag "Reset my password!", class: "btn btn-primary btn-round" %>
                        <br/>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>