config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :login, to: 'sessions#new', as: 'login'
  delete :logout, to: 'sessions#destroy', as: 'logout'
  get :register, to: 'users#new', as: 'register'
  post :register, to: 'users#create'

  # External Authentication
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # Languge
  resources :languages, only: [] do
  	collection do
  		get	:english
  		get	:bahasa
  	end
  end

  scope "(:locale)" do
    resources :password_resets
	  resources	:users do
	  	member do
		    get :activate
		  end
		end
  	resources :sessions, except: [ :show ]

    resources :schedules do
      collection do
        get :redirect
        get :callback
        get :calendars
        post :events
        delete :reset
        post :import
      end
    end
    resources :events do
      member do
        # put :archive
        post :search_agenda
        put :set_date
      end
    end

    resources :invitations, only: [:create] do
      member do
        put :resent
      end
    end
	end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

	root 'dashboard#index'
end

app/views/layouts/shared/_authentication.html.erb
<nav class="navbar navbar-primary navbar-transparent navbar-absolute">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <%= t('app.name') %>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="<%= active_link('users') %>">
                    <%= link_to register_path do %>
                        <i class="material-icons">person_add</i> <%= t("authentication.register") %>
                    <% end %>
                </li>
                <li class="<%= active_link('sessions') %>">
                    <%= link_to login_path do %>
                        <i class="material-icons">fingerprint</i> <%= t("authentication.login") %>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="wrapper wrapper-full-page">
    <div class="full-page <%= params[:controller].eql?('sessions') ? 'login-page' : 'register-page' %>" filter-color="black" data-image="<%= image_path('mail-bg.jpg') %>">
        <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
        
        <%= yield %>
        
        <%= render 'layouts/shared/footer' %>
    </div>
</div>

<% content_for :javascripts do %>
	<script type="text/javascript">
	    $(document).ready(function() {
	        setTimeout(function() {
	            // after 1000 ms we add the class animated to the login/register card
	            $('.card').removeClass('card-hidden');
	        }, 700)
	    });
	</script>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
    <div class="<%= logged_in? ? 'container-fluid' : 'container' %>">
        <nav class="pull-left">
            <ul>
                <li>
                    <%= link_to_unless I18n.locale == :id, "Bahasa Indonesia", bahasa_languages_path %>
                </li>
                <li>
                    <%= link_to_unless I18n.locale == :en, "English", english_languages_path %>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <%= Time.now.year %>
            <a href="#">achmadrifaldi.xyz</a>
        </p>
    </div>
</footer>

app/views/layouts/shared/_main.html.erb
<%= content_for :button_fixed %>
<div class="wrapper">
    <%= render 'layouts/shared/sidebar' %>
	<div class="main-panel">
		<%= render 'layouts/shared/top_nav' %>
		<div class="content">
			<div class="container-fluid">
				<%= yield %>
			</div>
		</div>
		<%= render 'layouts/shared/footer' %>
	</div>
</div>

app/views/layouts/shared/_sidebar.html.erb
<div class="sidebar" data-active-color="purple" data-background-color="white">
    <div class="logo">
        <a href="#" class="simple-text">
            <%#= t("app.name") %>
            Tik Tok
        </a>
    </div>
    <div class="logo logo-mini">
        <a href="#" class="simple-text">
            <%#= t("app.name") %>
            TT
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <%= image_tag(current_user.avatar.thumb.url) %>
            </div>
            <div class="info">
                <br/>
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    <%= current_user.fullname %>
                    <b class="caret"></b>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li>
                            <%= link_to 'My Profile', edit_user_path(id: current_user.id) %>
                        </li>
                        <li>
                            <%= link_to 'Sign out', logout_path, method: :delete %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="<%= active_link('schedules') %>">
                <%= link_to schedules_path, title: 'Schedule' do %>
                    <i class="material-icons">schedule</i>
                    <p>Agenda</p>
                <% end %>
            </li>            
            <li class="<%= active_link('events') %>">
                <%= link_to events_path, title: 'Events' do %>
                    <i class="material-icons">event</i>
                    <p>Events</p>
                <% end %>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/shared/_top_nav.html.erb
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons visible-on-sidebar-mini">view_list</i>
            </button>
        </div>
        <div class="navbar-header" data-turbolinks="false">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-turbolinks-permanent>
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <%= content_for :page_title %>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- <li>
                    <%#= link_to edit_user_registration_path(current_user) do %>
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    <%# end %>
                </li> -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="hidden-lg hidden-md">
                            Notifications
                            <b class="caret"></b>
                        </p>
                    </a>
                    <!-- <ul class="dropdown-menu">
                        <li>
                            <a href="#">You don't have notification</a>
                        </li>
                    </ul> -->
                </li>
                <li class="separator hidden-lg hidden-md"></li>
            </ul>
            <%= content_for :search_bar %>
        </div>
    </div>
</nav>