config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :login, to: 'sessions#new', as: 'login'
  delete :logout, to: 'sessions#destroy', as: 'logout'
  get :register, to: 'users#new', as: 'register'
  post :register, to: 'users#create'

  # External Authentication
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # Languge
  resources :languages, only: [] do
  	collection do
  		get	:english
  		get	:bahasa
  	end
  end

  scope "(:locale)" do
    resources :password_resets
	  resources	:users do
	  	member do
		    get :activate
		  end
		end
  	resources :sessions, except: [ :show ]

    resources :schedules do
      collection do
        get :redirect
        get :callback
        get :calendars
        post :events
        delete :reset
        post :import
      end
    end
    resources :events do
      member do
        # put :archive
        post :search_agenda
        put :set_date
      end
    end

    resources :invitations, only: [:create] do
      member do
        put :resent
      end
    end
	end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

	root 'dashboard#index'
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  start_at   :datetime
#  end_at     :datetime
#  all_day    :boolean          default(FALSE)
#  label      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  sync_id    :string
#  provider   :string
#

class Schedule < ApplicationRecord
  belongs_to :user

  def self.between(start_time, end_time)
    where('start_at > :lo and start_at < :up',
      :lo => start_time.to_date.to_formatted_s(:db),
      :up => end_time.to_date.to_formatted_s(:db)
    )
  end

  def self.format_date(date_time)
   Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def as_json(options = {})
    {
      id: self.id,
      title: self.title,
      start: start_at.rfc822,
      end: end_at.rfc822,
      allDay: all_day,
      color: "green"
    }
  end

  def parsing_ical(user, file)
    cal_file = File.open(file)
    event_items = []

    # Parser returns an array of calendars because a single file
    # can have multiple calendars.
    cals = Icalendar::Calendar.parse(cal_file)
    cals.each do |cal|
      cal.events.each do |event|
        start_at = event.dtstart
        end_at = event.dtend

        event_items << {
          user_id: user.id,
          title: event.summary,
          start_at: start_at,
          end_at: end_at,
          sync_id: event.uid,
          provider: 'google'
        } 
      end
    end

    Schedule.create(event_items)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_action :set_schedule, only: [:show, :edit, :update, :destroy]

	def index
		@schedules = current_user.schedules.between(params['start'], params['end']) if (params['start'] && params['end']) 
		respond_to do |format| 
      format.html
      format.json { render :json => @schedules } 
    end
	end

	def create
		@schedule = Schedule.new(schedule_params)
		@schedule.user_id = current_user.id
		@schedule.save
	end

	def update
		@schedule.update_attributes(schedule_params)
	end

	def destroy
		@schedule.destroy
		respond_to do |format| 
      format.html { redirect_to schedules_path }
      format.js
    end
	end

  def reset
    current_user.schedules.destroy_all
  end

	def redirect
    client = Signet::OAuth2::Client.new({
      client_id: Rails.application.config.sorcery.google.key,
      client_secret: Rails.application.config.sorcery.google.secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: callback_schedules_url
    })

    redirect_to client.authorization_uri.to_s
  end

  def callback
    client = Signet::OAuth2::Client.new({
      client_id: Rails.application.config.sorcery.google.key,
      client_secret: Rails.application.config.sorcery.google.secret,
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      redirect_uri: callback_schedules_url,
      code: params[:code]
    })

    response = client.fetch_access_token!

    puts response.inspect
    session[:authorization] = response

    redirect_to calendars_schedules_url
  end

  def calendars
    client = Signet::OAuth2::Client.new({
      client_id: Rails.application.config.sorcery.google.key,
      client_secret: Rails.application.config.sorcery.google.secret,
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
    })

    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @calendar_list = service.list_calendar_lists
  end

  def events
    client = Signet::OAuth2::Client.new({
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
    })

    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    unless params[:cal_ids].blank?
    	calendar_ids = params[:cal_ids]
    	event_items = []

    	calendar_ids.each do |calendar_id|
    		@event_list = service.list_events(calendar_id)
    		@event_list.items.each do |event|
    			start_at = event.start.date_time || event.start.date
    			end_at = event.end.date_time || event.end.date

    			event_items << {
    				user_id: current_user.id,
    				title: event.summary,
    				start_at: start_at.to_datetime,
    				end_at: end_at.to_datetime,
    				sync_id: event.i_cal_uid,
    				provider: 'google'
    			} 
    		end
    	end

    	Schedule.create(event_items)
    end

    redirect_to schedules_path
  end

  def import
    
  end

	private

	def set_schedule
		@schedule = current_user.schedules.where(id: params[:id]).first
	end

	def schedule_params
		params.require(:schedule).permit(:id, :user_id, :title, :start_at, :end_at, :all_day, :label)
	end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/calendars.html.erb
<div class="header text-center">
    <h3 class="title">Choose calendar to import</h3>
    <p class="category">
    </p>
</div>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="card">
			<%= form_tag events_schedules_path do %>
				<div class="card-content">
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th></th>
									<th class="text-center">Summary</th>
									<th class="text-center">Calendar ID</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<% @calendar_list.items.each do |calendar| %>
									<tr>
			            	<td class="text-center">
			                <div class="checkbox">
			                  <label>
			                  	<%= check_box_tag "cal_ids[]", calendar.id, (calendar.primary ? true : false) %>
			                  </label>
			                </div>
			              </td>
			              <td><%= calendar.summary %></td>
			              <td><%= calendar.id %></td>
			              <td><%= calendar.primary ? '<span class="btn btn-xs btn-success">PRIMARY</span>'.html_safe : '' %></td>
			          	</tr>
		          	<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<div class="card-footer text-right">
					<button class="btn btn-primary" type="submit">
						<i class="material-icons">sync</i> Import now
					</button>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/schedules/index.html.erb
<div class="row">
	<div class="col-xs-7 col-md-offset-1">
		<%= link_to redirect_schedules_path, class: 'btn btn-primary' do %>
			<i class="material-icons">sync</i> Sync google calendar
		<% end %>
	</div>
	<div class="col-xs-3 text-right">
		<%= link_to '#', class: 'btn btn-default btn-round btn-fab btn-fab-mini dropdown-toggle', data: { toggle: 'dropdown' }, style: 'margin: 10px 0 10px;' do %>
			<i class="material-icons">settings</i>
		<% end %>
		<ul class="dropdown-menu">
      <li><%#= link_to 'Import iCal', '#' %></li>
      <li><%= link_to 'Reset Schedule', '#', id: 'resetSchedule' %></li>
    </ul>
	</div>
	<div class="col-md-10 col-md-offset-1">
		<div class="card card-calendar">
			<div class="card-content">
				<div id="calendar"></div>
			</div>
		</div>
	</div>
</div>