config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :login, to: 'sessions#new', as: 'login'
  delete :logout, to: 'sessions#destroy', as: 'logout'
  get :register, to: 'users#new', as: 'register'
  post :register, to: 'users#create'

  # External Authentication
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # Languge
  resources :languages, only: [] do
  	collection do
  		get	:english
  		get	:bahasa
  	end
  end

  scope "(:locale)" do
    resources :password_resets
	  resources	:users do
	  	member do
		    get :activate
		  end
		end
  	resources :sessions, except: [ :show ]

    resources :schedules do
      collection do
        get :redirect
        get :callback
        get :calendars
        post :events
        delete :reset
        post :import
      end
    end
    resources :events do
      member do
        # put :archive
        post :search_agenda
        put :set_date
      end
    end

    resources :invitations, only: [:create] do
      member do
        put :resent
      end
    end
	end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

	root 'dashboard#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                :integer          not null, primary key
#  name              :string
#  description       :text
#  attendance        :integer
#  location          :string
#  start_at          :datetime
#  start_at_timezone :string
#  end_at            :datetime
#  end_at_timezone   :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Event < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  has_many :invitations

  scope :owned, -> { where("memberships.is_admin = true") }
  scope :invited, -> { where("memberships.is_admin = false") }

  def event_admin?(user)
  	memberships.where(user_id: user, is_admin: true).count > 0
  end

  def search_optimize_date(dstart, dend)
  	selected_date = dstart.to_date..dend.to_date
  	assemblage = {}

  	user_schedules = {}
  	users.each do |member|
  		user_schedules["#{member.id}"] = member.schedules.map{|schedule| (schedule.start_at.to_date..schedule.end_at.to_date).to_a}.flatten.uniq
  	end

  	selected_date.each do |ddate|
  		assemblage["#{ddate}"] = 0
  		user_schedules.each do |user_id, availability|
  			assemblage["#{ddate}"] += 1 unless availability.include?(ddate.to_date)
  		end
  	end

  	return assemblage
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :search_agenda, :set_date]
  def index
    @event_owned = current_user.events.owned
    @event_invited = current_user.events.invited
  end

  def show
    @invitation = Invitation.new
    @is_admin = @event.event_admin?(current_user.id)
    @event_start_at = @event.start_at.strftime("%B %d, %Y") rescue nil
  end

  def new
    @event = Event.new
  end

  def edit;end

  def create
    @event = Event.new(event_params)
    if @event.save
      Membership.new_member_admin(@event.id, current_user.id)
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully deleted.'
  end

  # def archive;end

  def search_agenda
    dstart = params[:start_date].to_date
    dend = params[:end_date].to_date
    @agendas = @event.search_optimize_date(dstart, dend)
  end

  def set_date
    @event.update_attribute(:start_at, params[:date].to_datetime)
    redirect_to event_path(id: @event.id), notice: 'Event date was successfully updated.'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:id, :name, :description, :attendance, :location, :start_at, :start_at_timezone, :end_at, :end_at_timezone)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/shared/_agenda.html.erb
<div class="card">
	<div class="card-header">
		<div class="form-group label-floating">
	    <label class="control-label">Event Date</label>
	    <%= text_field_tag :name, @event_start_at, class: 'form-control', disabled: true, required: true %>
	  	<span class="material-input"></span>
	  </div>
	</div>
	<% if @is_admin %>
		<div class="card-header">
			<h4 class="card-title">Search Date</h4>
		</div>
	  <%= form_tag search_agenda_event_path(id: @event.id), remote: true, class: 'form-horizontal' do %>
	  	<div class="card-content">
	  		<div class="row">
			  	<%= hidden_field_tag :start_date %>
			  	<%= hidden_field_tag :end_date %>
			  	<div class="col-md-6">
				    <div id="rangedate" class="btn btn-block btn-primary">
						  <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
						  <span></span> 
						  <b class="caret"></b>
						</div>
					</div>
					<div class="col-md-6">
						<button type="submit" class="btn btn-fill btn-primary">
							<i class="material-icons">search</i> Search
						</button>
					</div>
				</div>
		  </div>
		<% end %>

		<div id="result"></div>
	<% end %>
</div>

app/views/events/shared/_description.html.erb
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Event Information</h4>
  </div>
  <div class="card-content">
    <div class="form-group label-floating">
	    <label class="control-label">Event Name</label>
	    <%= text_field_tag :name, @event.name, class: 'form-control', disabled: true, required: true %>
	  	<span class="material-input"></span>
	  </div>
	  <div class="form-group label-floating">
	    <label class="control-label">Event Summary</label>
	    <%= text_area_tag :description, @event.description, class: 'form-control', disabled: true, required: true %>
	    <span class="material-input"></span>
	  </div>
	  <div class="form-group label-floating">
	    <label class="control-label">Attendance</label>
	    <%= text_field_tag :attendance, @event.attendance, class: 'form-control', disabled: true, required: true %>
	  	<span class="material-input"></span>
	  </div>
	  <div class="form-group label-floating">
	    <label class="control-label">Location</label>
	    <div id="map"></div>
	  </div>
  </div>
</div>

app/views/events/shared/_event.html.erb
<div class="col-md-4">
    <div class="card card-product">
        <div class="card-image" data-header-animation="true">
            <a href="#pablo">
            	<%= image_tag("sample.jpg", class: "event-#{event.id}") %>
            </a>
        </div>
        <div class="card-content">
            <div class="card-actions">
                <%= link_to event_path(id: event.id), class: "btn btn-default btn-simple", data: { placement: "bottom", original: { title: "View" } }, rel: "tooltip", title: "View" do %>
                    <i class="material-icons">art_track</i>
                <% end %>
                <% if event.event_admin?(current_user.id) %>
                    <%= link_to edit_event_path(id: event.id), class: "btn btn-success btn-simple", data: { placement: "bottom", original: { title: "Edit" } }, rel: "tooltip", title: "Edit" do %>
                        <i class="material-icons">edit</i>
                    <% end %>
                    <%= link_to edit_event_path(id: event.id), class: "btn btn-danger btn-simple", data: { placement: "bottom", original: { title: "Remove" } }, rel: "tooltip", title: "Remove" do %>
                        <i class="material-icons">close</i>
                    <% end %>
                <% end %>
            </div>
            <h4 class="card-title">
                <a href="#pablo"><%= event.name %></a>
            </h4>
            <div class="card-description">
            </div>
        </div>
        <div class="card-footer">
            <div class="price">
                <h4></h4>
            </div>
            <div class="stats pull-right">
                <p class="category">
                    <i class="material-icons">group</i> <%= event.users.count %> / <%= event.attendance %>
                </p>
            </div>
        </div>
    </div>
</div>


<%= content_for :javascripts do %>
  <% lat_lang = event.location.delete(" ") rescue nil %>
  <% unless lat_lang.blank? %>
    <script type="text/javascript">
        $(document).ready(function(){
          url = "//maps.googleapis.com/maps/api/staticmap?center=<%= lat_lang %>&size=196x147&markers=color:red%7Clabel:S%7C<%= lat_lang %>&sensor=true&zoom=15&scale=2&key=AIzaSyA7qw8ESOxqUHIrLNZqnmoVffWlakvhmdg"
          $('.event-<%= event.id %>').attr('src', url);
        });
    </script>
  <% end %>
<% end %>

app/views/events/shared/_form.html.erb
<div class="card-content">
	<h4 class="card-title">&nbsp;</h4>
  <div class="form-group label-floating">
    <label class="control-label">Event Name</label>
    <%= form.text_field :name, class: 'form-control', required: true %>
  	<span class="material-input"></span>
  </div>
  <div class="form-group label-floating">
    <label class="control-label">Event Summary</label>
    <%= form.text_area :description, class: 'form-control', required: true %>
    <span class="material-input"></span>
  </div>
  <div class="form-group label-floating">
    <label class="control-label">Attendance</label>
    <%= form.number_field :attendance, class: 'form-control', required: true %>
  	<span class="material-input"></span>
  </div>
  <div class="form-group">
    <label class="control-label">Location</label>
    <%= form.hidden_field :location, id: 'location' %>
    <div class="row">
      <div class="col-md-9">
        <%= text_field_tag :search_location, nil, id: 'search_location', class: 'form-control', placeholder: 'Search Location'  %>
      </div>
      <div class="col-md-3">
        <%= link_to '#', class: 'btn btn-primary', id: 'searchMap' do %>
          <i class="material-icons">search</i> Search
        <% end %>
      </div>
    </div>
    <div id="map"></div>
  </div>
</div>
<div class="card-footer text-right">
	<%= link_to events_path, class: "btn btn-default" do %>
		<i class="material-icons">close</i> Cancel
	<% end %>
	<button type="submit" class="btn btn-fill btn-primary">
		<i class="material-icons">check</i> Save
	</button>
</div>

<%= content_for :javascripts do %>
  <script type="text/javascript">
    <% lat_lang = @event.location.delete(" ").split(",") rescue [] %>
    var map;
    $(document).ready(function(){
      map = new GMaps({
        div: '#map',
        lat: <%= lat_lang.first || '-12.043333' %>,
        lng: <%= lat_lang.second || '-77.028333' %>,
        click: function(e) {
            map.removeMarkers();
            $('#location').val(e.latLng.lat()+", "+e.latLng.lng());
            map.addMarker({
              lat: e.latLng.lat(),
              lng: e.latLng.lng(),
              title: 'Event Location',
            });
        }
      });

      map.addMarker({
        lat: <%= lat_lang.first || '-12.043333' %>,
        lng: <%= lat_lang.second || '-77.028333' %>,
        title: 'Event Location',
      });

      GMaps.geolocate({
        success: function(position){
            map.setCenter(position.coords.latitude, position.coords.longitude);
        },
        error: function(error){
            khronos.showNotification('danger', 'Geolocation failed: ' + error.message);
        },
        not_supported: function(){
            khronos.showNotification('danger', "Your browser does not support geolocation");
        },
        always: function(){}
      });

      $('body').on('click', '#searchMap', function(e){
        GMaps.geocode({
          address: $("#search_location").val().trim(),
          callback: function(results, status){
            if(status=='OK'){
              map.removeMarkers();
              var latlng = results[0].geometry.location;
              map.setCenter(latlng.lat(), latlng.lng());
              map.addMarker({
                lat: latlng.lat(),
                lng: latlng.lng()
              });
              $('#location').val(latlng.lat()+", "+latlng.lng());
            }
          }
        });
      });
    });
  </script>
<% end %>

app/views/events/shared/_memberships.html.erb
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Member List</h4>
  </div>
  <div class="card-content">
  	<div class="form-horizontal">
  		<%= form_for @invitation do |f| %>
		    <%= f.hidden_field :event_id, value: @event.id %>
		    <div class="row">
          <div class="col-xs-4 col-xs-offset-5">
              <div class="form-group label-floating is-empty">
                <label class="control-label"></label>
                <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
             		<span class="material-input"></span>
              </div>
          </div>
          <div class="col-xs-3">
          	<button type="submit" class="btn btn-fill btn-primary btn-block">
							<i class="material-icons">email</i> Invite
						</button>
          </div>
        </div>
			<% end %>
  	</div>
    <table class="table table-striped">
    	<thead>
    		<tr>
    			<th>#</th>
    			<th>Name</th>
    			<th>Email</th>
    			<th>Status</th>
    		</tr>
    	</thead>
    	<tbody>
    		<% @event.invitations.each_with_index do |invitation, index| %>
    			<tr>
    				<td><%= index + 1 %></td>
    				<td><%= invitation.recipient.fullname rescue '-' %></td>
    				<td><%= invitation.email %></td>
    				<td>
    					<span class="btn btn-xs btn-info">
    						<%= invitation.recipient.blank? ? 'pending' : 'member' %>
    					</span>
    					<%= link_to resent_invitation_path(id: invitation.id), method: :put, class: 'btn btn-xs btn-primary' do %>
    						<i class="material-icons">email</i> Re Invite
    					<% end if invitation.recipient.blank?  %>
    				</td>
    			</tr>
    		<% end %>
    	</tbody>
    </table>
  </div>
</div>

app/views/events/shared/_result.html.erb
<div class="card-header">
    <h4 class="card-title"></h4>
</div>
<div class="card-content">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Date</th>
				<th class="text-center">Attendance</th>
				<th class="text-right">Action</th>
			</tr>
		</thead>
		<tbody>
			<% agendas.each do |key, val| %>
				<tr>
					<td><%= key %></td>
					<td class="text-center"><%= val %></td>
					<td class="text-right">
						<%= link_to set_date_event_path(id: event.id, date: key), method: :put, class: 'btn btn-xs btn-info' do %>
							<i class="material-icons">check</i> set
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>